server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/noaa-wetter/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/noaa-wetter/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /var/www/noaa-wetter/public;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' https://unpkg.com; img-src 'self' data: https://{s}.tile.openstreetmap.org https://tilecache.rainviewer.com; connect-src 'self' https://api.rainviewer.com https://warnung.bund.de https://nina.api.proxy.bund.dev https://api.open-meteo.com https://maps.dwd.de;";

    location /data/ {
        try_files $uri =404;
        default_type application/json;
    }

    location ^~ /nina/api31/ {
        proxy_pass https://warnung.bund.de/api31/;
        proxy_set_header Host warnung.bund.de;
        proxy_ssl_server_name on;
        proxy_set_header User-Agent "Mozilla/5.0";
        proxy_set_header Accept-Encoding "";
        proxy_buffering on;
    }

    location / {
        try_files $uri /index.html;
    }
}
